### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius-gpt-bot#1]
Hi Jeff, Many thanks for putting this together, it's working great with my OpenAI api.

Not found any issues so far but will keep my eye out and let you know.

One suggestion might be referencing the [hotline icon document](https://wiki.preterhuman.net/Hotline_Icons) to help people find the right icon id.

Also as a potential future version the ability to use [Ollama](https://ollama.com/) api for local (private and free) GPT generation.

Thanks again 👍🏼 

EDIT: Just found an issue, if you restart your mobius docker container the bot container crashes. Some kinda server validation/check needed? 

EDIT:EDIT: May be linked to this issue: https://github.com/jhalter/mobius/issues/124

**Comment by jhalter** [comment]
Hi Ade,
 
> One suggestion might be referencing the [hotline icon document](https://wiki.preterhuman.net/Hotline_Icons) to help people find the right icon id.

Thanks for the link, done.

> Also as a potential future version the ability to use [Ollama](https://ollama.com/) api for local (private and free) GPT generation.

Agree, I think it'd be nice to be able to swap out the AI API backend.

>  if you restart your mobius docker container the bot container crashes.

It's true that the bot exits if it loses its server connection.  I run it as an auto-restarting systemd service, so this hasn't come up as a problem for me.  I could consider adding an option to reconnect.
