### ISSUE TITLE
Private messages get no response.

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius-gpt-bot#2]
Hi Jeff,
I've been testing after a RetroMac [user via Mastodon](https://mastodon.gamedev.place/@gingerbeardman/112899261018095543) mentioned they weren't getting any response from the bot via private message.  I can confirm that the logs are showing receiving the message and a response but nothing is being sent back to the user/client.

I'm using the Mierau's Hotline client to test. 

![Screenshot 2024-08-09 at 14 05 27](https://github.com/user-attachments/assets/ea61fb80-673b-4f34-9181-e0ed6486a52c)

Responses via Chat is working fine and shows similar logs.

**Comment by jhalter** [comment]
Hey Ade, thanks for the report.  

I can't seem to reproduce this for my bot.  Any chance the bot account is missing the permission to send messages?  If that's not it, I'll add some more logging to better capture what's happening.

**Comment by aptonline** [comment]
Doh! that was it. All fixed 👍🏼

**Comment by jhalter** [comment]
I'll make sure this logs something instead of silently failing.
