### ISSUE TITLE
Abandon config file and command line flags in favor of environment variables

### ISSUE THREAD

**Issue by jhalter** [jhalter/mobius-gpt-bot#3]
I've moved my own bot instance from a systemd service to Docker, but the current file based configuration is inconvenient as it requires a volume mount to read the config file from the host OS.

Proposal:

Make a breaking change to drop support for the config file and command line flags for server, login, pass.  Instead, read everything from environment vars.

**Comment by aptonline** [comment]
I see you’ve made the changes, so docs need updated to support?

**Comment by jhalter** [comment]
Yeah, I pushed ahead with this.  Feels right.  

I've updated the README with the new environment vars.  I also added OPENAI_MODEL and defaulted to the cheaper `gpt-4o-mini` model instead of `gpt-4o`.  I haven't noticed a difference in functionality and cheaper seems good!

**Comment by aptonline** [comment]
All upgraded, replied to your post on RetroMac with an observation regarding setting multiline environmental settings.
